### ISSUE TITLE
This repository seems to be out of date 

### ISSUE THREAD

**Issue by berkakinci** [STMicroelectronics/OpenOCD#12]
I am having trouble using openocd gdb server remotely with STM32CubeIDE.  I can not build a matching version, because this repository appears to be behind the shipping version.
Please update this repository.

This is the version that is shipped with it STM32CubeIDE:
```
Open On-Chip Debugger 0.11.0+dev-00449-g53fa0f7 (2022-06-09-09:45) [https://github.com/STMicroelectronics/OpenOCD]
Licensed under GNU GPL v2
```

**Comment by tarek-bochkati** [comment]
dear @berkakinci 
Thanks for reporting this,
we updated the `openocd-cubeide-r5` branch with latest openocd code integrated in STM32CubeIDE
you can also check the project [tags](https://github.com/STMicroelectronics/OpenOCD/tags) to build a specific version.
