### ISSUE TITLE
stlink_usb Assertion `handle != NULL' failed

### ISSUE THREAD

**Issue by AlefeFelipe** [STMicroelectronics/OpenOCD#3]
In src/jtag/drivers/stlink_usb.c:1169 - stlink_usb_mode_leave: Assertion `handle != NULL' failed.

This happen when I try execute a mass erase command using **flash erase_sector** or **stm32l4x mass_erase**. 

The null pointer is passed hardcode to the stlink_dap_arp_init function when there's a STLINK_SWD_AP_STICKY_ERROR

**Target**: stm32wbx
**Interface**: stlink

**Comment by tarek-bochkati** [comment]
Thanks for reporting this behavior
This answer might be late, the issue was fixed in this branch:
https://github.com/STMicroelectronics/OpenOCD/tree/openocd-cubeide-r2
