### ISSUE TITLE
Failed to read memory

### ISSUE THREAD

**Issue by AlefeFelipe** [STMicroelectronics/OpenOCD#4]
Failed to read memory at 0x080f6004

This happen when I try execute a read command using **flash read_bank**.

**Target**: stm32wbx
**Interface**: raspberrypi2-native (SWD)

If I use the same command, but with st-link as interface, it works

**Comment by tarek-bochkati** [comment]
Thanks for reporting the issue.
Unfortunately raspberrypi2-native is not supported in this fork.

Could you please report this issue in official openocd bug tracker:
https://sourceforge.net/p/openocd/tickets/
